version: "3"
services:
  db:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: postgres
      environment:
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "taehi"
      volumes:
        - "./data:/var/lib/postgresql/data"
      ports:
        - 5432:5432
  test-springboot:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db